<?php
function bbcode2html($content) {
    $content = htmlspecialchars($content);
    $content = preg_replace('/\[ul\](\s*)\[li\]/is', '[ul][li]', $content);
    $content = preg_replace('/\[ol\](\s*)\[li\]/is', '[ol][li]', $content);
    $content = preg_replace('/(\s+)\[\/url\]/is', '[/url]'."\n", $content);
    $content = str_replace('[:)]', '<img src="static/editor/emoticons/smile.svg" alt="Smile" title="Smile" style="width: 24px;line-height: 0;vertical-align: middle;"/>', $content);
    $content = str_replace('[:tear-joy]', '<img src="static/editor/emoticons/tear_joy.svg" alt="Tear-Joy" title="Tear-Joy" style="width: 24px;line-height: 0;vertical-align: middle;"/>', $content);
    $content = str_replace('[:angry:]', '<img src="static/editor/emoticons/angry.svg" alt="Angry" title="Angry" style="width: 24px;line-height: 0;vertical-align: middle;"/>', $content);
    $content = str_replace('[;)]', '<img src="static/editor/emoticons/wink.svg" alt="Wink" title="Wink" style="width: 24px;line-height: 0;vertical-align: middle;"/>', $content);
    $content = str_replace('[:love]', '<img src="static/editor/emoticons/love.svg" alt="Love" title="Love" style="width: 24px;line-height: 0;vertical-align: middle;"/>', $content);
    $content = str_replace('[:dog]', '<img src="static/editor/emoticons/dog.svg" alt="Dog" title="Dog" style="width: 24px;line-height: 0;vertical-align: middle;"/>', $content);
    $content = preg_replace('/\[b\](.*?)\[\/b\]/is', '<b>$1</b>', $content);
    $content = preg_replace('/\[i\](.*?)\[\/i\]/is', '<i>$1</i>', $content);
    $content = preg_replace('/\[u\](.*?)\[\/u\]/is', '<u>$1</u>', $content);
    $content = preg_replace('/\[s\](.*?)\[\/s\]/is', '<strike>$1</strike>', $content);
    $content = preg_replace('/\[sub\](.*?)\[\/sub\]/is', '<sub>$1</sub>', $content);
    $content = preg_replace('/\[sup\](.*?)\[\/sup\]/is', '<sup>$1</sup>', $content);
    $content = preg_replace('/\[left\](.*?)\[\/left\]/i', '<p style="text-align: left;">$1</p>', $content);
    $content = preg_replace('/\[center\](.*?)\[\/center\]/i', '<p style="text-align: center;">$1</p>', $content);
    $content = preg_replace('/\[right\](.*?)\[\/right\]/i', '<p style="text-align: right;">$1</p>', $content);
    $content = preg_replace('/\[justify\](.*?)\[\/justify\]/is', '<div style="text-align: justify;">$1</div>', $content);
    $content = preg_replace('/\[ul\](.*?)\[\/ul\](\s*)/is', '<ul>$1</ul>', $content);
    $content = preg_replace('/\[ol\](.*?)\[\/ol\](\s*)/is', '<ol>$1</ol>', $content);
    $content = preg_replace('/\[li\](.*?)\[\/li\](\s*)/is', '<li>$1</li>', $content);
    $content = preg_replace('/\[hr\]/is', '<hr />', $content);
    $content = preg_replace('/\[url\]((?:https?:)?\/?\/[^\s\'"]+?)\[\/url\]/is', '<a href="$1" target="_blank" rel="nofollow noopener noreferrer">$1</a>', $content);
    $content = preg_replace('/\[url=((?:https?:)?\/?\/[^\s\'"]+?)\](.*?)\[\/url\]/is', '<a href="$1" target="_blank" rel="nofollow noopener noreferrer">$2</a>', $content);
    $content = preg_replace('/\[img\]((?:https?:)?\/?\/[^\s\'"]+?)\[\/img\]/i', '<img class="lazyload" data-src="$1" style="max-width:300px;" />', $content);
    $content = preg_replace('/\[img=(\d+)x(\d+)\]((?:https?:)?\/?\/[^\s\'"]+?)\[\/img\]/i', '<img class="lazyload" data-src="$3" width="$1px" height="$2px" style="max-width:300px;" />', $content);
    $content = preg_replace('/\[font.*\](.*?)\[\/font\]/is', '$1', $content);
    $content = preg_replace('/\[quote\](.*?)\[\/quote\]/is', '<blockquote>$1</blockquote>', $content);
    $content = preg_replace('/\[code\](.*?)\[\/code\]/is', '<code>$1</code>', $content);
    $content = preg_replace('/\[size=(\d+)\](.*?)\[\/size\]/i', '<font size="$1;">$2</font>', $content);
    $content = preg_replace('/\[color=(#[a-f0-9]{6}|#[a-f0-9]{3}|[a-z]+)\](.*?)\[\/color\]/i', '<span style="color: $1;">$2</span>', $content);
    $content = preg_replace('/(\n+)/is', '<br />', $content);
    return $content;
}

function html2bbcode($content) {
    $content = str_replace('<br />', "\n", $content);
    $content = str_replace('<img src="static/editor/emoticons/smile.svg" alt="Smile" title="Smile" style="width: 24px;line-height: 0;vertical-align: middle;"/>', '[:)]', $content);
    $content = str_replace('<img src="static/editor/emoticons/tear_joy.svg" alt="Tear-Joy" title="Tear-Joy" style="width: 24px;line-height: 0;vertical-align: middle;"/>', '[:tear-joy]', $content);
    $content = str_replace('<img src="static/editor/emoticons/angry.svg" alt="Angry" title="Angry" style="width: 24px;line-height: 0;vertical-align: middle;"/>', '[:angry:]', $content);
    $content = str_replace('<img src="static/editor/emoticons/wink.svg" alt="Wink" title="Wink" style="width: 24px;line-height: 0;vertical-align: middle;"/>', '[;)]', $content);
    $content = str_replace('<img src="static/editor/emoticons/love.svg" alt="Love" title="Love" style="width: 24px;line-height: 0;vertical-align: middle;"/>', '[:love]', $content);
    $content = str_replace('<img src="static/editor/emoticons/dog.svg" alt="Dog" title="Dog" style="width: 24px;line-height: 0;vertical-align: middle;"/>', '[:dog]', $content);
    $content = preg_replace('/\<b\>(.*?)\<\/b\>/is', '[b]$1[/b]', $content);
    $content = preg_replace('/\<i\>(.*?)\<\/i\>/is', '[i]$1[/i]', $content);
    $content = preg_replace('/\<u\>(.*?)\<\/u\>/is', '[u]$1[/u]', $content);
    $content = preg_replace('/\<strike\>(.*?)\<\/strike\>/is', '[s]$1[/s]', $content);
    $content = preg_replace('/\<sub\>(.*?)\<\/sub\>/is', '[sub]$1[/sub]', $content);
    $content = preg_replace('/\<sup\>(.*?)\<\/sup\>/is', '[sup]$1[/sup]', $content);
    $content = preg_replace('/\<p style="text-align: left;"\>(.*?)\<\/p\>/i', '[left]$1[/left]', $content);
    $content = preg_replace('/\<p style="text-align: center;"\>(.*?)\<\/p\>/i', '[center]$1[/center]', $content);
    $content = preg_replace('/\<p style="text-align: right;"\>(.*?)\<\/p\>/i', '[right]$1[/right]', $content);
    $content = preg_replace('/\<div style="text-align: justify;"\>(.*?)\<\/div\>/is', '[justify]$1[/justify]', $content);
    $content = preg_replace('/\<ul\>(.*?)\<\/ul\>/is', '[ul]$1[/ul]', $content);
    $content = preg_replace('/\<ol\>(.*?)\<\/ol\>/is', '[ol]$1[/ol]', $content);
    $content = preg_replace('/\<li\>(.*?)\<\/li\>/i', '[li]$1[/li]', $content);
    $content = preg_replace('/\<hr\>/is', '[hr]', $content);
    $content = preg_replace('/\<font size=\"(\d+);\"\>(.*?)\<\/font\>/i', '[size=$1]$2[/size]', $content);
    $content = preg_replace('/\<span style=\"color\: (#[a-f0-9]{6}|#[a-f0-9]{3}|[a-z]+);\"\>(.*?)\<\/span\>/is', '[color=$1]$2[/color]', $content);
    $content = preg_replace('/\<img class="lazyload" data-src=\"((?:https?:)?\/?\/[^\s\'"]+?)\" style=\"(.*?)\"\ \/>/is', '[img]$1[/img]', $content);
    $content = preg_replace('/\<img class="lazyload" data-src=\"((?:https?:)?\/?\/[^\s\'"]+?)\" width=\"(\d+px)\" height=\"(\d+px)\" style=\"(.*?)\"\ \/>/i', '[img=$2x$3]$1[/img]', $content);
    $content = preg_replace('/\<code\>(.*?)\<\/code\>/is', '[code]$1[/code]', $content);
    $content = preg_replace('/\<blockquote\>(.*?)\<\/blockquote\>/is', '[quote]$1[/quote]', $content);
    $content = preg_replace('/\<a href=\"((?:https?:)?\/?\/[^\s\'"]+?)\" (.*?)\>(.*?)\<\/a\>/is', '[url=$1]$3[/url]', $content);
    return $content;
}
